### ISSUE TITLE
Private Properties/Methods

### ISSUE THREAD

**Issue by Link2Twenty** [webcomponents/beta#545]
There is no way (that I can see) to show private API's. Though this is not generally necessary for using an element it often helps to understand what is happening in the background.

[Origin page](https://beta.webcomponents.org/element/Link2Twenty/l2t-paper-slider/l2t-paper-slider)

**Comment by andymutton** [comment]
We took the view here that internal implementation details shouldn't appear in the catalog.

We find, as devs, that when someone reaches a point where they want to know what's going on under the hood, they really want to go all-in, and will ultimately go digging through the source anyway.

Also, from a philosophical perspective, the published API really IS the interface; publishing anything private would violate encapsulation. One of the benefits of custom elements IS the encapsulation, so we wanted to respect that.

Having said that, we do have some ideas for improving the API documentation, such as grouping by behavior/mixin/inheritance (to show where the code is really coming from) and showing html attribute names with the properties (because confusion still exists around this for first time users).

I'm closing this for now, but we'll be very happy to revisit it if time proves us wrong.
