### ISSUE TITLE
Please delete this collections

### ISSUE THREAD

**Issue by JosefJezek** [webcomponents/beta#598]
https://beta.webcomponents.org/collection/StartPolymer/awesome-charts
https://beta.webcomponents.org/collection/StartPolymer/awesome-buttons

I renamed this collections to 

awesome-chart-elements
awesome-button-elements

Thank you

**Comment by JosefJezek** [comment]
https://beta.webcomponents.org/collection/StartPolymer/awesome-buttons
https://beta.webcomponents.org/collection/StartPolymer/awesome-charts

are still live...

**Comment by samuelli** [comment]
@JosefJezek: it's a bit deceiving!

They are deleted, but the service worker caches these responses and doesn't update since they now return 404s.

If you use `ctrl+shift+r` it'll purge the cache.

I'm not sure what a good fix is since we don't want to cache 404s. Perhaps we want to remove from cache if we get an error another time. @dstockwell WDYT? The only case this occurs are repo renames and deletions. Another fix might be to return `moved`, or `deleted` not as 400s.

**Comment by samuelli** [comment]
Incognito is also a good check to ignore the service worker.

**Comment by samuelli** [comment]
@dstockwell: ideally in renames we should redirect to the new name.
