### ISSUE TITLE
Inline demo contains "```html"

### ISSUE THREAD

**Issue by tomalec** [webcomponents/beta#750]
As you can see at https://beta.webcomponents.org/element/Juicy/juicy-ace-editor
![image](https://cloud.githubusercontent.com/assets/17435/21606416/aa528c58-d1af-11e6-88d8-c1be6055d2bb.png)
Inline demo contains "```html"
The markdown looks like follows:

````markdown
3. Start using it!
<!--
 ```
<custom-element-demo>
  <template>
    <link rel="import" href="juicy-ace-editor.html">
    <next-code-block></next-code-block>
  </template>
</custom-element-demo>
```
-->
    ```html
    <juicy-ace-editor>Editable code here</juicy-ace-editor>
    ```
````

I suppose indentation is the problem, but I'd like to keep it to get formatting right in regular markdown result.

**Comment by samuelli** [comment]
@tomalec: the markdown formatting doesn't look correct on GitHub.

![image](https://cloud.githubusercontent.com/assets/787668/21701238/a1570a0c-d3f8-11e6-95b9-15295432ef0b.png)
Ref: https://github.com/Juicy/juicy-ace-editor

You may need an extra newline before the commented section. For the README files, the site uses GitHub to render it, so this issue might be fixed once it looks correct on GitHub. Can you try that? You can use preview instead of publishing a new version.

**Comment by tomalec** [comment]
Thanks @samuelli, I have just fixed formattin so it looks good in github, but at beta.webcomponents.org I still have the same problem

The corrected markdown looks like:

````markdown
3. Start using it!

   <!--
   ```
   <custom-element-demo>
     <template>
       <script src="../webcomponentsjs/webcomponents.js"></script>
       <link rel="import" href="juicy-ace-editor.html">
       <next-code-block></next-code-block>
     </template>
   </custom-element-demo>
   ```
   -->

  ```html
  <juicy-ace-editor theme="ace/theme/monokai">Type your code here...</juicy-ace-editor>
  ```
````

BTW, Can I refresh the beta.wc.org page without releasing a new version?

**Comment by samuelli** [comment]
@tomalec: this is fixed now!

https://beta.webcomponents.org/element/Juicy/juicy-ace-editor

**Comment by tomalec** [comment]
Great! thanks
